config/routes.rb
Rails.application.routes.draw do
  get 'registered_application/show'

  get 'registered_application/new'

  devise_for :users
  get 'welcome/index'
  resources :registered_applications

  root to: "welcome#index"

  namespace :api, defaults: { format: :json} do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController


   before_filter :set_access_control_headers

   def set_access_control_headers

     headers['Access-Control-Allow-Origin'] = '*'

     headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'

     headers['Access-Control-Allow-Headers'] = 'Content-Type'
   end

  skip_before_action :verify_authenticity_token

  def create
    @registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    if !@registered_application
      render json: "Unregistered application", status: :unprocessable_entity
    end
    @event = @registered_application.events.new(event_params)
    if @event.save!
      render json: @event, status: :created
    else
      render json: {errors: @event.errors}, status: :unprocessable_entity
    end
  end

  def preflight
    head 200
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @registered_applications = RegisteredApplication.all
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
    @events = @registered_application.events.group_by(&:name)
  end

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = RegisteredApplication.new(params[:registered_application].permit!)
    @registered_application.save!
    redirect_to registered_application_path(@registered_application)
  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])
    @registered_application.delete
    redirect_to registered_applications_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  has_many :registered_applications
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_application_helper.rb
module RegisteredApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<span class = "pull-right"><% if current_user %>
   Signed in as: <strong><%= current_user.email %></strong> |
   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <% else %>
   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
 <% end %></span>
<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>

app/views/registered_application/index.html.erb
<% registered_applications.each do |app| %>
<%= link_to app.name registered_application_path(app) %>
<% end %>

app/views/registered_application/new.html.erb
<h3>Register a New Application</h3>
<%= form_for @registered_application do |f| %>
<%= f.text_field :name %>
<% end %>

app/views/registered_applications/index.html.erb
<h2>Registered Applications</h2>
<%= link_to "Register New Application", new_registered_application_path, class: 'btn btn-success' %></br>
<% @registered_applications.each do |app| %>
<%= link_to app.name, registered_application_path(app) %></br>
<% end %>

app/views/registered_applications/new.html.erb
<h2>Register a New Application</h2>
<%= form_for @registered_application do |f| %>
Application Name <%= f.text_field :name %></br>
Application URL <%= f.text_field :url %></br>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.submit "Register Application" %>
<% end %>

app/views/registered_applications/show.html.erb
<h2><%= @registered_application.name %></h2>
<h4><%= @registered_application.url %></h4>
<h3>Events</h3>
<% @events.each do |key, value| %>
<%= key %>(<%= value.length %>)</br>
<% end %>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%= pie_chart @registered_application.events.group(:name).count %>

<%= line_chart @registered_application.events.group_by_day(:created_at).count %>


<h4><%= link_to "Deregister Application", @registered_application, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to deregister this application?'} %></h4>
<%= link_to "Back to All Applications", registered_applications_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>